# Generated by Django 3.2.4 on 2021-06-18 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finhelp', '0004_auto_20210617_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='b3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='ValAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_b3', models.CharField(blank=True, max_length=10)),
                ('valor', models.FloatField()),
                ('data_atualizacao', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('perc_change', models.FloatField()),
                ('val_ant', models.FloatField()),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
