# Generated by Django 3.2.4 on 2021-06-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finhelp', '0005_auto_20210618_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valativo',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
