# Generated by Django 3.2.4 on 2021-06-18 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finhelp', '0006_alter_valativo_data_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valativo',
            name='fk_b3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finhelp.ativo'),
        ),
    ]
