# Generated by Django 3.2.4 on 2021-06-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finhelp', '0009_auto_20210618_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='perc_change',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='val_ant',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='valor',
        ),
        migrations.CreateModel(
            name='ValAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('perc_change', models.FloatField()),
                ('val_ant', models.FloatField()),
                ('fk_ativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finhelp.ativo')),
            ],
        ),
    ]
