# Generated by Django 3.2.4 on 2021-06-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finhelp', '0010_auto_20210618_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValAtivo',
            new_name='HistAtivo',
        ),
    ]
