# Generated by Django 3.2.4 on 2021-06-19 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finhelp', '0011_rename_valativo_histativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='histativo',
            name='last_hist',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='b3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='histativo',
            name='data_atualizacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='histativo',
            name='fk_ativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finhelp.ativo'),
        ),
    ]
